# Generated by Django 3.2.5 on 2021-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210803_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ext_user',
            name='ismanager',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
