# Generated by Django 3.2.5 on 2021-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='location',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
